---
- name: Deploy Docker container on EC2
  hosts: ec2
  become: yes

  vars:
    IMAGE: "rahul0315/devops-nodejs-app:{{ (GIT_COMMIT | default('latest'))[:7] }}"
    CONTAINER_NAME: devops-app
    APP_PORT: 3000

  tasks:
    - name: Check if Docker is already installed
      shell: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install apt dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: docker_installed.rc != 0

    - name: Add Docker's GPG key (secure method)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_installed.rc != 0

    - name: Add Docker APT repository (use jammy even on noble)
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable'
        state: present
      when: docker_installed.rc != 0

    - name: Update APT cache
      apt:
        update_cache: yes
      when: docker_installed.rc != 0

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
      when: docker_installed.rc != 0

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove existing container if exists
      shell: "docker rm -f {{ CONTAINER_NAME }} || true"

    - name: Pull image
      shell: "docker pull {{ IMAGE }}"

    - name: Run container with 80:3000 mapping
      shell: "docker run -d --name {{ CONTAINER_NAME }} -p 80:{{ APP_PORT }} {{ IMAGE }}"
